### ISSUE TITLE
scraper-sync load causing flapping alerts

### ISSUE THREAD

**Issue by stephen-soltesz** [m-lab/scraper-sync#41]
While investigating the flapping of alerts for mil03, I found that almost all Scraper targets were flapping into and out of a "pending" state for the "ScraperCollectorMissingFromScraperSync". This implied that prometheus was not receiving the complete status from scraper sync. After more investigation, it appears that since the new nodebase package with the new delete_logs_safely.py was deployed 2017-10-02 evening, the CPU usage on scraper-sync is at the limit for the node (~50% of one core) every hour during the 15-minute randomize period used by scraper-sync.

During that period, requests to `/metrics` are slow enough to prevent prometheus from scraping successfully. There are evident gaps in the prometheus logs for ~20 minutes at a time. These gaps trigger alerts indirectly.

![node-cpu](https://user-images.githubusercontent.com/1085316/31143771-5ab0b52a-a84c-11e7-894a-55ef2dfd6fed.png)

**Comment by gfr10598** [comment]
We are adding a new sync-pool, with more resources, and changing the resource requests in the kubernetes config for scraper-sync.

Starting with staging...
1. Find the appropriate label by looking at current node:
kubectl get pods
kubectl describe pod scraper-sync-... | less   (then find the node)
kubectl describe node gke-scraper-cluster-default-pool-... | less (then find the node label)

2. Create new node-pool with larger machines:
gcloud --project=mlab-staging container node-pools create scraper-sync-pool --cluster=scraper-cluster --num-nodes=2 --node-labels=scraper-node=true -m n1-highcpu-8

3. Update the sync.yaml file to include cpu and memory requests...  (PR #42)
        resources:
            requests:
              memory: "5Gi"
              cpu: "4"
            limits:
              memory: "8Gi"
              cpu: "8"

REPEAT FOR PROD:
gcloud --project=mlab-oti container node-pools create scraper-sync-pool --cluster=scraper-cluster --num-nodes=2 --node-labels=scraper-node=true -m n1-highcpu-8

**Comment by gfr10598** [comment]
Oops - left out a critical parameter, and realized we need a different label:

gcloud --project=mlab-staging container node-pools create scraper-sync-pool --zone "us-central1-a" --machine-type "n1-highcpu-8" --scopes "https://www.googleapis.com/auth/cloud-platform","https://www.googleapis.com/auth/spreadsheets" --num-nodes "2" --node-labels=scraper-sync-node=true --cluster=scraper-cluster

**Comment by gfr10598** [comment]
Also adding a prometheus request counter in PR #43

**Comment by gfr10598** [comment]
To look at prometheus metrics from the scraper-sync job:

Find the prometheus federation:
http://status-mlab-oti.measurementlab.net:9090/targets
   look for federation, on the scraper-cluster
go to the link, stripping off the "federation"

Looking at cpu usage:
sum(rate(container_cpu_usage_seconds_total{container_name="scraper-sync"}[2m]))
Looking at request rates (per minute):
sum by (message)(60*rate(requests[2m]))

**Comment by gfr10598** [comment]
http://35.188.22.107:9090/graph?g0.range_input=1h&g0.expr=sum(rate(container_cpu_usage_seconds_total%7Bcontainer_name%3D%22scraper-sync%22%7D%5B2m%5D))&g0.tab=0&g1.range_input=1h&g1.expr=sum+by+(message)(60.0*rate(requests%5B2m%5D))&g1.tab=0&g2.range_input=1h&g2.expr=process_virtual_memory_bytes%7Bcontainer%3D%22scraper-sync%22%7D&g2.tab=0

**Comment by gfr10598** [comment]
The changes to node configs have not helped.  cpu utilization now hovers around 1.5 for about the first 30 minutes of each hour, which is *longer* than before.  
During that interval, prometheus metric collection is completely stalled for the entire time.

Over that 30 minutes there are the following requests (roughly)
  1900 json
  120 collectd
    60 request errors (bad requests?)
      0 root url

Memory consumption occasionally jumps.  Initially it was about 300MB, then 2GB, now 6GB.

**Comment by gfr10598** [comment]
Peter made a major change in PR #45, to only fetch the full state from datastore, and cache it with a 30 second timeout.  This is triggered by either json requests from the delete_logs_safely jobs, or by prometheus collections every minute.  This was deployed at approximately 20:03 UTC.

This has greatly reduced the load on scraper-sync, and the CPU utilization is now around 0.20.

**Comment by gfr10598** [comment]
New version of delete_logs_safely deployed around 20:40 UTC.  It adds a lock to ensure that only one copy of DLS is running at any one time.  This should reduce both cpu and I/Os.

An additional change to DLS is canarying tonight.  It changes the delete mechanism to use find -delete, which eliminates the huge number of vserver calls (for each individual rm).  This should radically reduce the cpu load and probably disk I/Os on the servers.

**Comment by stephen-soltesz** [comment]
There was a bug in last night's dls canary that deleted empty directories that we need to not be deleted. That is now fixed (https://github.com/m-lab/nodebase-private/pull/64/files) and the fix is in canary again this evening.

**Comment by stephen-soltesz** [comment]
The scraper-sync load appears to be resolved.
